from iiif_prezi3 import Manifest, Canvas, AnnotationPage, Annotation, ResourceItem, config

config.configs['helpers.auto_fields.AutoLang'].auto_lang = "en"

manifest_url = "https://raw.githubusercontent.com/kpaw-man/images-serving/main/skull-3d-manifest-prezi3.json"
canvas_id = f"{manifest_url}/canvas/0"
anno_page_id = f"{canvas_id}/annotationpage/0"
anno_id = f"{canvas_id}/annotation/0"

manifest = Manifest(id=manifest_url, label="Example generated by prezi3")

canvas = Canvas(id=canvas_id)

anno_body = ResourceItem(id="https://collections.st-andrews.ac.uk/media/403185/403185.glb",
                        format="model/gltf-binary",
                         type="Model")

anno_page = AnnotationPage(id=anno_page_id)

anno = Annotation(id=anno_id,
                  motivation="painting",
                  body=anno_body,
                  target=canvas.id)

anno_page.add_item(anno)
canvas.add_item(anno_page)
manifest.add_item(canvas)

print(manifest.json(indent=2))
